export declare function asyncMatchReadDir(path: string, match: RegExp, isDep: boolean): NodeJs.AsyncPromise;
export declare function asyncMatchReadDir(path: string, isDep: boolean): NodeJs.AsyncPromise;
export declare function asyncReadDir(path: string): NodeJs.AsyncPromise;
export declare function asyncEachDir(path: string, isDep: boolean, beginPaths?: string[]): NodeJs.AsyncPromise;
export declare function asyncIsDir(path: string): NodeJs.AsyncPromise;
declare type asyncEachCB<T> = (item: T, index: number, self: T[]) => void;
export declare function asyncEach<T>(list: T[], fn?: asyncEachCB<T>): Promise<void>;
export declare function iterateArray<T>(arr: T[], dispose: (item: T, index: number, next: Function) => void): void;
export declare function iterate(dispose: (next: () => void) => void): void;
export {};
